version = 0.1
[default.deploy.parameters]
stack_name = "is-steve-knight-mowing"
resolve_s3 = true
s3_prefix = "is-steve-knight-mowing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
